@DientesLimpios.API_HostAddress = http://localhost:5088/api/consultorios

GET {{DientesLimpios.API_HostAddress}}/019D6B91-3F7E-7389-B857-BBB8D9DFA6A9
Accept: application/json

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "nombre" : "Consultorio A"
}